name: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.name
partial: recipe
tabs:
    fields:
        prologue:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.prologue
            type: richeditor
            size: huge

        category:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.detail
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.category

        cuisine:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.detail
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.cuisine

        servings:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.detail
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.servings

        serving_calories:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.detail
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.serving_calories

        prep_time_hours:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.timing
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.prep_time_hours
            span: left
            type: dropdown
            options: \Dynamedia\Posts\Classes\Helpers\Form::getHours

        prep_time_minutes:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.timing
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.prep_time_minutes
            span: right
            type: dropdown
            options: \Dynamedia\Posts\Classes\Helpers\Form::getMinutes

        cook_time_hours:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.timing
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.cook_time_hours
            span: left
            type: dropdown
            options: \Dynamedia\Posts\Classes\Helpers\Form::getHours

        cook_time_minutes:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.timing
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.cook_time_minutes
            span: right
            type: dropdown
            options: \Dynamedia\Posts\Classes\Helpers\Form::getMinutes

        total_time_hours:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.timing
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.total_time_hours
            span: left
            type: dropdown
            options: \Dynamedia\Posts\Classes\Helpers\Form::getHours

        total_time_minutes:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.timing
            label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.total_time_minutes
            span: right
            type: dropdown
            options: \Dynamedia\Posts\Classes\Helpers\Form::getMinutes



        ingredients_form:
            type: nestedform
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.ingredients
            showPanel: false
            usePanelStyles: false
            form:
                secondaryTabs:
                    fields:
                        ingredients:
                            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.ingredients_list
                            type: repeater
                            form:
                                fields:
                                    name:
                                        label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.name
                                    amount:
                                        label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.amount

                        ingredients_image:
                            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.ingredients_image
                            type: mediafinder
        method_intro:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.method
            label: Method Introduction
            type: richeditor

        method_steps:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.method
            type: repeater
            form:
                fields:
                    step_title:
                        label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.step_title
                    step_detail:
                        label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.step_detail
                    step_image:
                        label: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.labels.image
                        type: mediafinder

        epilogue:
            tab: theme.dynamedia-postsdemo::lang.postbody_templates.recipe.tabs.epilogue
            type: richeditor
            size: huge








